config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  
  resources :articles do
    resources :comments
  end
  
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    default_scope {order(created_at: :desc)}

    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, dependent: :destroy
  belongs_to :user, dependent: :destroy

  validates :body ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    #change the default error page for RecordNotFound 
    rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

    protected
    def resource_not_found
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def index
        @articles = Article.all
    end

    def show
        @comments = @article.comments.all
        @comment = @article.comments.build
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            redirect_to articles_path
            flash[:success] = "Article has been created"
        else
            flash[:danger] = 'Article has not been created'
            render :new
        end
    end

    def edit
        unless @article.user == current_user
            flash[:alert] = 'You can only edit your own article.'
            redirect_to root_path
        end
    end

    def update
        unless @article.user == current_user
            flash[:alert] = 'You can only edit your own article.'
            redirect_to root_path
        else
            if @article.update(article_params)
                redirect_to @article
                flash[:success] = 'Article has been updated'
            else
                flash[:danger] = 'Article has not been updated'
                render :edit
            end
        end
    end

    def destroy
        unless @article.user == current_user
            flash[:alert] = 'You can only delete your own articles.'
            redirect_to root_path
        else
            @article.destroy
            flash[:success] = 'Article successfully deleted'
            redirect_to root_path
        end
    end

    protected
        def resource_not_found
            message = 'The article you are looking for could not be found'
            flash[:alert] = message
            redirect_to root_path
        end

    private
        def article_params
            params.require(:article).permit(:title, :body)
        end
        
        def set_article
            @article = Article.find(params[:id])
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
    def create
        unless current_user
            flash[:alert] = 'Please sign in or sign up first'
            redirect_to new_user_session_path
        else
            @comment = @article.comments.build(comment_params) 
            @comment.user = current_user
            if @comment.save
                ActionCable.server.broadcast "comments",
                render(partial: 'comments/comment', object: @comment ) 
                flash[:notice] = "Comment has been created"
                #redirect_to article_path(@article)
            else
                flash.now[:alert] = "Comment has not been created"
                redirect_to new_user_session_path
            end
        end 
    end

    private
        def comment_params
            params.require(:comment).permit(:body)
        end
        def set_article
            @article = Article.find(params[:article_id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

    def persisted_comments(comments) 
        comments.reject{ |comment| comment.new_record? }    
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-error alert-block">
        #{messages}
      </div>
     HTML
   html.html_safe
 end
end 

app/views/articles/_form.html.erb
<div class='row'>
    <div class='col-md-12'>
        <%= form_for(article, :html => {class: 'form-horizontal', role: 'form'}) do |a| %>
        <% if article.errors.any? %>
            <div class='row'>
                <div class='col-md-8 col-md-offset-2'>
                    <div class='panel panel-danger'>
                        <div class='panel-heading'>    
                            <h2 class='panel-title'> 
                                <%= pluralize(article.errors.count, 'error')%>
                                prohibited this <%= article.class %> from being saved:
                            </h2>
                            <div class='panel-body'>            
                                <ul>
                                    <% article.errors.full_messages.each do |msg| %>
                                        <li> <%= msg %> </li>
                                    <% end %>
                                <ul>  
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        <% end %>
        <div class='form-group'>
           <div class='control-label col-md-1'>
                <%= a.label :title %>
            </div>
            <div class='col-md-11'>
                <%= a.text_field :title, class: 'form-control', placheolder:'Title of article', autofocus: true %>
            </div>
        </div>


        <div class='form-group'>
            <div class='control-label col-md-1'>
                <%= a.label :body %>
            </div>
            <div class='col-md-11'>
                <%= a.text_area :body, class: 'form-control', rows: 10, placheolder:'Body of article'%>
            </div>
        </div>
        <%= a.submit class: 'btn btn-primary btn-lg pull-right'%>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h3 class='text-center'>Edit article </h3>

<%= render 'articles/form', article: @article%>

app/views/articles/index.html.erb
<h1>This is the articles page</h1>
<% if user_signed_in? %>
    <%= link_to 'New Article', new_article_path, class: 'btn btn-default btn-lg', id: 'new-article-button'%>
<% end %>
<% if @articles.count > 0 %>
    <% @articles.each do |article| %>
        <div class='well well-lg'>
            <div class='article-title'>
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class='article-body'>
                <%=truncate(article.body, length: 500) %>
            </div>
            <div class='author'>
                <small>Created by: <%= article.user.email %> </small>
            </div>
        </div>
    <% end %> 
<% else %>
    <h1 id='no-articles'>No Articles Created</h1>
<% end %>

app/views/articles/new.html.erb
<h3 class='text-center'>Adding new article </h3>
<%= render 'articles/form', article: @article%>

app/views/articles/show.html.erb
<article class='detail-article'>
    <div class='well well-lg'>
        <h1 class='article-detail-title text-primary'>
            <%= @article.title %>
        </h1>

        <div class='glyphicon glyphicon-calender' id='article-date'>
            <%= @article.created_at.strftime("%b %d %Y")%>
        </div> <br>
        
        <div class='article-body'>
            <%= @article.body %>
        </div>
        <% if current_user == @article.user %>
            <div class='edit-delete'>
                <%= link_to 'Edit Article', edit_article_path(@article), class: 'btn btn-primary btn-lg btn-space' %>
                <%= link_to 'Delete Article', article_path(@article),method: :delete, class: 'btn btn-danger btn-lg btn-space', data: {confirm: 'Are you sure'} %>
            </div>
        <% end %>
</article class>

<hr>

<div class='col-md-12'>
    <%= form_for [@article, @comment], remote: true, :html => {class: 'form-horizontal', route: 'form'} do |f| %>
        <% if @comment.errors.any? %>
            <div class='panel panel-danger col-md-offset-1'>
                <div class='panel-heading'>
                    <h2 class='panel-title'> 
                        <%= pluralize(@comment.errors.count, 'error') %>
                        prohibited this comment from being saved:
                    </h2>
                    <div class='panel-body'>
                        <ul>
                            <% @comment.errors.full_messages.each do |msg| %>
                            <li> <%= msg %> </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        <% end %>
        <div class='form-group'>
            <div class='control-label col-md-2'>
                <%= f.label :body, 'New Comment' %>
            </div>
            <div class='col-md-10'>
                <%= f.text_area :body, rows: 6, class: 'form-control', placeholder: 'Your comment' %>
            </div>
        </div>
        <div class='form-group'>
            <div class='col-md-offset-2 col-md-10'>
                <%= f.submit 'Add Comment', class: 'btn btn-primary btn-lg pull-right'%>
            </div>
        </div>
    <%end%>
</div>

<div class='col-md-12'>
    <header>
        <h2>Comments:</h2>
    </header>
    <div class='col-md-10'>
        <% if @article.comments.any? %>
            <div id='messages'>
                <% persisted_comments(@comments).each do |comment| %>
                    <div class='well'>
                        <div class='comment-body'>
                            <%= comment.body %>
                        </div>
                        <div class='comment-time'>
                            <%= time_ago_in_words(comment.created_at) %>
                            ago by <%= comment.user.email%>
                        </div>
                    </div>
                    <hr>
                <% end %>
            <% else %>
                There are no comments to show
            <% end %>
        </div>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class='well'>
    <div class='comment-body'>
        <%= comment.body %>
    </div>
    <div class='comment-time'>
        <%= time_ago_in_words(comment.created_at) %>
        ago by <%= comment.user.email%>
    </div>
    <hr>
</div>

app/views/layouts/_messages.html.erb
<div class='row'>
    <div class='col-md-10 col-md-offset-1'>
        <% flash.each do |type, message| %>
        <% if type === 'alert'%>
        <div class='alert alert-danger'>
            <a href='#' class='close' data-dismiss='alert'>&#215;</a>
            <%= message %>
        </div>
        <% else %>
        <div class="alert alert-info" role='alert'>
            <a href='#' class='close' data-dismiss='alert'>&#215;</a>
            <%= message %>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header role="banner">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid"> 
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"                data-target="#bs-example-navbar-collapse-1"> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <%= link_to "Blog App", root_path, class: "navbar-brand" %> 
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Authors", "#" %></li>
                <% if user_signed_in? %>
                    <p class='navbar-text'>
                        Signed in as <%= "#{current_user.email}"%>
                    </p>
                    <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
                <% else %>
                    <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
                    <li> <%= link_to 'Sign In', new_user_session_path %> </li>
                <% end %>
                </ul> 
            </div>
        </div> 
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/navigation'%> <br> 
      <%= render 'layouts/messages' %> 
      <%= yield %> 
    </div>
  </body>
</html>